apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: zookeeper-app
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      containers:
      - name: zookeeper-container
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: zookeeper-app
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: follower
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: leader
      protocol: TCP
      port: 3888
      targetPort: 3888