apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: kafka-app
  ports:
    - name: kafka-default-port
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server-deployment
spec:
  selector:
    matchLabels:
      app: kafka-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - name: kafka-container
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper_ready=$(echo stat | nc zookeeper-cluster-ip 2181 | grep Mode); if [ -z \"$zookeeper_ready\" ]; then exit 1; fi"
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster-ip:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-cluster-ip:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-cluster-ip
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        
        # This means that each message will be stored on a single broker in the cluster. 
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"

        - name: KAFKA_LOG_DIRS
          value: /kafka/logs
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1000000"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1000000"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_DEFAULT_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "1"
