# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-engine-pod
  
  template:
    metadata:
      labels:
        app: banking-engine-pod
    spec:
      containers:
      - name: banking-engine-container
        image: 476917393332.dkr.ecr.us-east-1.amazonaws.com/banking-engine:dev
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 1024Mi
            cpu: 1500m
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ecr-registry-creds
