# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-service-pod
  
  template:
    metadata:
      labels:
        app: logs-service-pod
    spec:
      containers:
      - name: logs-service-container
        image: 476917393332.dkr.ecr.us-east-1.amazonaws.com/logs-service:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3008
        resources:
          requests:
            memory: 128Mi
            cpu: 125m
          limits:
            memory: 1024Mi
            cpu: "500m"
      imagePullSecrets:
      - name: ecr-registry-creds
