# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-engine-pod
  
  template:
    metadata:
      labels:
        app: blockchain-engine-pod
    spec:
      containers:
      - name: blockchain-engine-container
        image: 476917393332.dkr.ecr.us-east-1.amazonaws.com/blockchain-engine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3012
        resources:
          requests:
            memory: 128Mi
            cpu: 125m
          limits:
            memory: 1024Mi
            cpu: "500m"
      imagePullSecrets:
      - name: ecr-registry-creds

