---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::476917393332:role/burency_dev_test-oidc
    #  system:serviceaccount:default:aws-test

---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-test
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/bash","-c","--"]
      args: ["while true; do sleep 30; done;"] #to prevent exit applied infinite loop 
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  tolerations:
    - operator: Exists
      effect: NoSchedule

